mutation AddRole($code: String!) {
  account {
    addRoleByCode(where: {}, code: $code)
  }
}

query GetAccountProperties($id: ID!) {
  account {
    getUser(where: {id: $id}) {
      blocked
    }
  }
}
